language: node_js
node_js:
  - "8.0.0"
services:
  - postgresql
before_script:
  - psql -c 'drop database if exists travis;' -U postgres
  - psql -c 'create database travis;' -U postgres
script:
  - npm run test
after_success: 
  - npm run coverage
